### ISSUE TITLE
Project links should open to new tab 

### ISSUE THREAD

**Issue by Ramona-Saintandre** [Juwana-Zerman/Django-Portfolio#19]
When you click on your project link it opens in the same tab, so then you have to use the back button to get back to your site 

![links open in new window](https://user-images.githubusercontent.com/55248847/137424155-5f4f5daf-5eda-44d0-89d7-537e07ee2aff.png)

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_target

**Comment by killerkc12** [comment]
I would like to work on this
And please add the hacktoberfest lebels because I'm participating in that program

**Comment by Juwana-Zerman** [comment]
Fixed with a recent update.
