### ISSUE TITLE
Blank spot 

### ISSUE THREAD

**Issue by ghost** [Juwana-Zerman/Django-Portfolio#20]
In your project section, there is a blank space 
needs to look into why 

![missing box](https://user-images.githubusercontent.com/55248847/137424259-188e3c93-7e9d-41a2-8767-e2641a20d078.png)

**Comment by Juwana-Zerman** [comment]
This spot is a placeholder for Azure projects. Currently there are only three. Projects are organized based on the Cloud Platform so there isn't anything else to add here at the moment.
