### ISSUE TITLE
Social media icons are to close 

### ISSUE THREAD

**Issue by Ramona-Saintandre** [Juwana-Zerman/Django-Portfolio#21]
Need some padding in for the social media icons 
They should be centered with the text 

![social media icons](https://user-images.githubusercontent.com/55248847/137424349-2052befb-6800-484d-8789-34c1ac9b64be.png)

**Comment by DKumar2169** [comment]
@Ramona-Saintandre I a new developer looking for projects to contribute too, I can do this can you assign this to me ?
